### ISSUE TITLE
Specify code license?

### ISSUE THREAD

**Issue by Pathoschild** [AdvizeGH/GetDressed#6]
The GetDressed code has no license, which means that nobody can legally update, modify, or re-release it without the permission of all contributors (not even the original authors). Proposed actions:

- [x] [Choose an open-source license](https://choosealicense.com/).
- [x] Get permission from all contributors to relicense code.
- [x] [Add a `LICENSE` file](https://help.github.com/articles/adding-a-license-to-a-repository/#including-an-open-source-license-in-your-repository).

**Comment by Jinxiewinxie** [comment]
Done! =)

**Comment by Pathoschild** [comment]
Thanks! And just to avoid any uncertainty later, I agree to relicense my contributions to GetDressed as GPL 3.0.
